services:
  # MVC
  nmnb-blue:
    build:
      context: .
      dockerfile: nmnb-bootstrap/Dockerfile
    container_name: nmnb-blue
    environment:
      - SERVER_PORT=${nmnb_BLUE_PORT}
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .prod_env
    ports:
      - "${nmnb_BLUE_PORT}:${MVC_INTERNAL_APP_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://nmnb-blue:${nmnb_BLUE_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nmnb_network

  nmnb-green:
    build:
      context: .
      dockerfile: nmnb-bootstrap/Dockerfile
    container_name: nmnb-green
    environment:
      - SERVER_PORT=${nmnb_GREEN_PORT}
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .prod_env
    ports:
      - "${nmnb_GREEN_PORT}:${MVC_INTERNAL_APP_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nmnb-green:${nmnb_GREEN_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nmnb_network

  dev-nmnb:
    build:
      context: .
      dockerfile: nmnb-bootstrap/Dockerfile
    container_name: dev-nmnb
    environment:
      - SERVER_PORT=${nmnb_DEV_PORT}
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .dev_env
    ports:
      - "${nmnb_DEV_PORT}:${MVC_INTERNAL_DEV_APP_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nmnb-green:${nmnb_DEV_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nmnb_network

  # WebFlux
  nmnb-webflux-blue:
    build:
      context: .
      dockerfile: nmnb-webflux-bootstrap/Dockerfile
    container_name: nmnb-webflux-blue
    environment:
      - SERVER_PORT=${nmnb_WEBFLUX_BLUE_PORT}
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .prod_env
    ports:
      - "${nmnb_WEBFLUX_BLUE_PORT}:${WEBFLUX_INTERNAL_APP_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nmnb-webflux-blue:${nmnb_WEBFLUX_BLUE_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nmnb_network

  nmnb-webflux-green:
    build:
      context: .
      dockerfile: nmnb-webflux-bootstrap/Dockerfile
    container_name: nmnb-webflux-green
    environment:
      - SERVER_PORT=${nmnb_WEBFLUX_GREEN_PORT}
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .prod_env
    ports:
      - "${nmnb_WEBFLUX_GREEN_PORT}:${WEBFLUX_INTERNAL_APP_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nmnb-webflux-green:${nmnb_WEBFLUX_GREEN_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nmnb_network

  dev-nmnb-webflux:
    build:
      context: .
      dockerfile: nmnb-webflux-bootstrap/Dockerfile
    container_name: dev-nmnb-webflux
    environment:
      - SERVER_PORT=${nmnb_WEBFLUX_DEV_PORT}
      - SPRING_PROFILES_ACTIVE=dev
    env_file:
      - .dev_env
    ports:
      - "${nmnb_WEBFLUX_DEV_PORT}:${WEBFLUX_INTERNAL_DEV_APP_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://nmnb-webflux-green:${nmnb_WEBFLUX_DEV_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - nmnb_network

networks:
  nmnb_network:
    external: true